moz_plus_project/home/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
)

from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="home"),
    path("accounts/login/", views.user_login, name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path(
        "accounts/password-change/",
        PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password-change-done/",
        PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("register/", views.subscriber_registration, name="register"),
    path(
        "content-creator/register/", views.creator_registration, name="register_creator"
    ),
    path("home/series/", views.series, name="series"),
    path(
        "home/series/<int:series_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "home/series/<int:series_id>/<int:season_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "home/series/<int:series_id>/<int:season_id>/<int:episode_id>/",
        views.episode_details,
        name="episode_details",
    ),
    path("home/movies/", views.movies, name="movies"),
    path("home/movie-info/<int:passed_id>/", views.movie_info, name="movie_info"),
    path(
        "home/movie-part/<int:movie_part_id>/",
        views.movie_part_details,
        name="movie_part_details",
    ),
]

moz_plus_project/moz_plus_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('super_admin.urls')),
    path('', include('subscriber.urls')),
    path('', include('content_creator.urls')),
    path('', include('content_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moz_plus_project/subscriber/urls.py
from django.urls import path

from . import views

app_name = 'subscriber'

urlpatterns = [
    path('subscriber/', views.subscriber, name='subscriber'),
    path('subscriber/series/', views.series, name='series'),
    path(
        "subscriber/series/<int:series_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "subscriber/series/<int:series_id>/<int:season_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "subscriber/series/<int:series_id>/<int:season_id>/<int:episode_id>/",
        views.episode_details,
        name="episode_details",
    ),
    path('subscriber/movies/', views.movies, name='movies'),
    path('subscriber/movie-info/<int:passed_id>/', views.movie_info, name='movie_info'),
    path('subscriber/movie-part/<int:movie_part_id>/', views.movie_part_details, name='movie_part_details'),
    path('subscriber/favourites/', views.favourites, name='favourites'),
]

moz_plus_project/subscriber/models.py
from django.db import models

from django.contrib.auth.models import User


# Create your models here.
class Subscriber(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField()
    phone_no = models.CharField(max_length=20, unique=True)
    country = models.ForeignKey("super_admin.Country", on_delete=models.CASCADE)
    image = models.ImageField(upload_to='subscriber/profile/images')
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class Subscription(models.Model):
    subscriber = models.OneToOneField(Subscriber, on_delete=models.CASCADE)
    plan = models.ForeignKey(
        "super_admin.SubscriptionPlan", 
        on_delete=models.CASCADE, 
        null=True,
        default=1
    )
    last_subscription = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.subscriber.user.username} : {self.plan.name}'

moz_plus_project/subscriber/forms.py
from django import forms

moz_plus_project/subscriber/views.py
from django.shortcuts import render
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect

from . import models
from . import forms

from content_management.forms import ShowRatingMoviePartForm, ShowRatingEpisodesForm
from content_management.models import FavouriteMovie, FavouriteSeries


# Create your views here.
@login_required
def subscriber(request):
    moz_user = models.Subscriber.objects.get(user=request.user)

    movies = apps.get_model("content_creator", "Movie").objects.all()
    series = apps.get_model("content_creator", "Series").objects.all()

    context = {
        "movies": movies,
        "series": series,
        "moz_user": moz_user,
    }

    return render(request, "subscriber/subscriber.html", context)


@login_required
def movies(request):
    moz_user = models.Subscriber.objects.get(user=request.user)

    search = request.GET.get("search")

    if search:
        content_movies = apps.get_model(
            app_label="content_creator", model_name="Movie"
        ).objects.filter(title__icontains=search)
    else:
        content_movies = apps.get_model(
            app_label="content_creator", model_name="Movie"
        ).objects.all()

    context = {
        "content_movies": content_movies,
        "moz_user": moz_user,
    }
    return render(request, "subscriber/movies.html", context)


@login_required
def movie_info(request, passed_id):
    moz_user = models.Subscriber.objects.get(user=request.user)

    content_movies = apps.get_model(
        app_label="content_creator", model_name="Movie"
    ).objects.get(id=passed_id)

    content_movies_part = apps.get_model(
        app_label="content_creator", model_name="MoviePart"
    ).objects.filter(movie_id=passed_id)

    context = {
        "content_movies": content_movies,
        "content_movies_part": content_movies_part,
        "moz_user": moz_user,
    }
    return render(request, "subscriber/movie_info.html", context)


@login_required
def movie_part_details(request, movie_part_id):
    moz_user = models.Subscriber.objects.get(user=request.user)

    content_movies_part = apps.get_model(
        app_label="content_creator", model_name="MoviePart"
    ).objects.get(id=movie_part_id)

    content_movie_rating = (
        apps.get_model(app_label="content_management", model_name="ShowRatingMoviePart")
        .objects.filter(subscriber=moz_user, movie_part=content_movies_part)
        .first()
    )

    content_movie_trailer = apps.get_model(
        app_label="content_creator", model_name="MovieTrailer"
    ).objects.filter(movie_part_id=movie_part_id)

    favourite = FavouriteMovie.objects.filter(
        subscriber=moz_user, movie_part=content_movies_part
    ).first()

    if content_movie_rating:
        rating_form = ShowRatingMoviePartForm(instance=content_movie_rating)
    else:
        rating_form = ShowRatingMoviePartForm()

    if "rating" in request.POST:
        rating_form = ShowRatingMoviePartForm(
            request.POST, instance=content_movie_rating
        )

        if rating_form.is_valid():
            new_form = rating_form.save(commit=False)
            new_form.subscriber = moz_user
            new_form.movie_part = content_movies_part
            new_form.save()
    elif "favourite" in request.POST:
        if favourite:
            favourite.delete()
            favourite = None
        else:
            favourite = FavouriteMovie.objects.create(
                subscriber=moz_user, movie_part=content_movies_part
            )

    context = {
        "moz_user": moz_user,
        "content_movies_part": content_movies_part,
        "content_movie_rating": content_movie_rating,
        "content_movie_trailer": content_movie_trailer,
        "rating_form": rating_form,
        "favourite": favourite,
    }
    return render(request, "subscriber/moviepart_details.html", context)


@login_required
def series(request):
    moz_user = models.Subscriber.objects.get(user=request.user)

    search = request.GET.get("search")

    if search:
        content_series = apps.get_model(
            app_label="content_creator", model_name="Series"
        ).objects.filter(title__icontains=search)
    else:
        content_series = apps.get_model(
            app_label="content_creator", model_name="Series"
        ).objects.all()

    context = {
        "content_series": content_series,
        "moz_user": moz_user,
    }
    return render(request, "subscriber/series.html", context)


@login_required
def series_details(request, series_id, season_id=None):
    moz_user = models.Subscriber.objects.get(user=request.user)

    content_series = apps.get_model(
        app_label="content_creator", model_name="Series"
    ).objects.get(id=series_id)

    content_seasons = apps.get_model(
        app_label="content_creator", model_name="Season"
    ).objects.filter(series_id=series_id)

    content_season_id = season_id or content_seasons.first().id

    content_season = apps.get_model(
        app_label="content_creator", model_name="Season"
    ).objects.get(id=content_season_id)

    content_episodes = apps.get_model(
        app_label="content_creator", model_name="Episodes"
    ).objects.filter(season_id=content_season_id)

    content_season_trailer = apps.get_model(
        app_label="content_creator", model_name="SeasonTrailer"
    ).objects.filter(season_id=content_season_id)

    favourite = FavouriteSeries.objects.filter(
        subscriber=moz_user, series=content_series
    ).first()

    if "favourite" in request.POST:
        if favourite:
            favourite.delete()
            favourite = None
        else:
            favourite = FavouriteSeries.objects.create(
                subscriber=moz_user, series=content_series
            )

    context = {
        "content_series": content_series,
        "content_season": content_season,
        "content_seasons": content_seasons,
        "content_episodes": content_episodes,
        "content_season_trailer": content_season_trailer,
        "moz_user": moz_user,
        "favourite": favourite,
    }
    return render(request, "subscriber/series_details.html", context)


@login_required
def episode_details(request, series_id, season_id, episode_id):
    moz_user = models.Subscriber.objects.get(user=request.user)

    content_episode = apps.get_model(
        app_label="content_creator", model_name="Episodes"
    ).objects.get(id=episode_id)

    content_episode_rating = (
        apps.get_model(app_label="content_management", model_name="ShowRatingEpisodes")
        .objects.filter(subscriber=moz_user, episodes=content_episode)
        .first()
    )

    if content_episode_rating:
        rating_form = ShowRatingEpisodesForm(instance=content_episode_rating)
    else:
        rating_form = ShowRatingEpisodesForm()

    if "rating" in request.POST:
        rating_form = ShowRatingEpisodesForm(
            request.POST, instance=content_episode_rating
        )

        if rating_form.is_valid():
            new_form = rating_form.save(commit=False)
            new_form.subscriber = moz_user
            new_form.episodes = content_episode
            new_form.save()

    context = {
        "content_episode": content_episode,
        "moz_user": moz_user,
        "rating_form": rating_form,
    }
    return render(request, "subscriber/episode_details.html", context)


@login_required
def favourites(request):
    moz_user = models.Subscriber.objects.get(user=request.user)
    favourite_movie = FavouriteMovie.objects.filter(subscriber=moz_user)
    favourite_series = FavouriteSeries.objects.filter(subscriber=moz_user)

    context = {
        "moz_user": moz_user,
        "favourite_movie": favourite_movie,
        "favourite_series": favourite_series,
    }
    return render(request, "subscriber/favourites.html", context)

moz_plus_project/subscriber/templates/subscriber/episode_details.html
{% extends 'home/base.html' %}

{% load crispy_forms_tags %}
{% block body %}
  {% include 'home/navbar.html' %}
  <div class="container">
    <div class="card bg-secondary">
      <img src="{{ content_episode.thumbnail.url }}" class="rounded" alt="{{ content_episode.slug }}" style="max-width: 100vw;" />
      <div class="card-img-overlay" style="background-color: rgba(0, 0, 0, 0.6);">
        <div class="row text-light h-100">
          <div class="col-6">
            <div class="fs-2 fw-bold">{{ content_episode.title }}</div>
          </div>
          <div class="col-6">
            <div class="d-flex flex-column justify-content-around h-100">
              <div class="row">
                <div class="col">
                  <div class="fs-5">Season: {{content_episode.season.season_no}}</div>
                </div>
                <div class="col">
                  <div class="fs-5">Episode: {{ content_episode.episode_no }}</div>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <div class="fs-5">Release Date</div>
                </div>
                <div class="col">
                  <div class="fs-6">{{ content_episode.release_date }}</div>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <div class="fs-5">Duration</div>
                </div>
                <div class="col">
                  <div class="fs-6">{{ content_episode.duration }}</div>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <div class="fs-5">Content Rating</div>
                </div>
                <div class="col">
                  <div class="fs-6">{{ content_episode.content_rating }}</div>
                </div>
              </div>
              <form action="" method="POST">
                {% csrf_token %}
                <div class="row">
                  <div class="col">
                    <label for="{{ rating_form.rating.id_for_label }}" class="form-label requiredField fs-5">Rating</label>
                  </div>
                  <div class="col">
                    <select name="{{ rating_form.rating.name }}" id="{{ rating_form.rating.id_for_label }}" class="form-select w-50" onchange="this.form.submit()">
                      {% for option in rating_form.rating.subwidgets %}
                        {{ option }}
                      {% endfor %}
                    </select>
                  </div>
                </div>
              </form>
              <a href="{{ content_episode.video.url }}" class="btn btn-primary"><i class="bi bi-play-btn fs-4"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card text-dark my-4">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <div class="card-text fs-4 fw-bold">Plot</div>
            <p class="card-text">{{ content_episode.plot }}</p>
          </div>
          <div class="col">
            <div class="row mb-2">
              <div class="col-4">
                <div class="card-text fs- fw-bold">Cast &amp; Crew</div>
              </div>
              <div class="col-8">
                {% for person in content_episode.person.all %}
                  <div class="row">
                    <div class="col">{{ person.show_person.first_name }} {{ person.show_person.last_name }}</div>
                    <div class="col">{{ person.role.name }}</div>
                  </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

moz_plus_project/subscriber/templates/subscriber/favourites.html
{% extends 'home/base.html' %}

{% block body %}
  {% include 'home/navbar.html' %}
  <nav>
    <div class="nav nav-tabs nav-justified" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-movie-tab" data-bs-toggle="tab" data-bs-target="#nav-movie" type="button" role="tab">Movie</button>
      <button class="nav-link" id="nav-series-tab" data-bs-toggle="tab" data-bs-target="#nav-series" type="button" role="tab">Series</button>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-movie" role="tabpanel" aria-labelledby="nav-movie-tab" tabindex="0">
        <div class="container my-2">
            <div class="row row-cols-1 row-cols-md-2 row-cols-md-3 row-cols-md-4 g-5">
                {% for movie in favourite_movie %}
                  <div class="col">
                    <a href="{% url 'subscriber:movie_part_details' movie.movie_part.id %}" class="text-decoration-none text-dark">
                      <div class="card big-item">
                        <img src="{{ movie.movie_part.thumbnail.url }}" class="card-img-top" height="200rem" alt="{{ movie.movie_part.title }}" />
                        <div class="card-body">
                          <div class="card-title">{{ movie.movie_part.title }}</div>
                        </div>
                      </div>
                    </a>
                  </div>
                {% endfor %}
              </div>
        </div>
    </div>
    <div class="tab-pane fade" id="nav-series" role="tabpanel" aria-labelledby="nav-series-tab" tabindex="0">
        <div class="container my-2">
            <div class="row row-cols-1 row-cols-md-2 row-cols-md-3 row-cols-md-4 g-5">
                {% for series in favourite_series %}
                  <div class="col">
                    <a href="{% url 'subscriber:series_details' series.series.id %}" class="text-decoration-none text-dark">
                      <div class="card big-item">
                        <img src="{{ series.series.image.url }}" class="card-img-top" height="200rem" alt="{{ series.series.title }}" />
                        <div class="card-body">
                          <div class="card-title">{{ series.series.title }}</div>
                        </div>
                      </div>
                    </a>
                  </div>
                {% endfor %}
              </div>
        </div>
    </div>
  </div>
{% endblock %}

moz_plus_project/subscriber/templates/subscriber/movie_info.html
{% extends 'home/base.html' %}

{% block body %}
  {% include 'home/navbar.html' %}
  <div class="container">
    <div class="card bg-secondary">
      <img src="{{ content_movies.image.url }}" class="rounded" alt="{{ content_movies.slug }}" width="250px" />
      <div class="card-img-overlay" style="background-color: rgba(0, 0, 0, 0.6);">
        <div class="row justify-content-between h-100">
          <h5 class="card-title fs-2">{{ content_movies.title }}</h5>
          <p class="card-text">{{ content_movies.overview }}</p>
        </div>
      </div>
    </div>

    <div class="container my-4">
      <div class="d-flex flex-row flex-nowrap overflow-auto">
        {% for movie_part in content_movies_part %}
          <div class="card mx-4" style="width: 22rem;">
            <div class="row g-0">
              <div class="col">
                <a href="{% url 'subscriber:movie_part_details' movie_part.id %}" class="text-decoration-none text-dark"><img src="{{ movie_part.thumbnail.url }}" class="card-img-top" alt="{{ movie_part.slug }}" /></a>
              </div>
              <div class="col">
                <div class="card-body text-dark">
                  <div class="d-flex flex-column justify-content-between" style="height: 14rem;">
                    <div class="card-title">{{ movie_part.title|slice:'20' }}</div>
                    <div class="card-text">Ratings: {{ movie_part.average_rating }}</div>
                    <a href="{{ movie_part.video.url }}" class="btn btn-primary"><i class="bi bi-play-btn"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

moz_plus_project/subscriber/templates/subscriber/movies.html
{% extends 'home/base.html' %}

{% block body %}
  {% include 'home/navbar.html' %}

  {% block style %}
    <style>
      .big-item {
        transition: transform 0.3s;
      }
      
      .big-item:hover {
        transform: scale(1.1);
      }
    </style>
  {% endblock %}

  <div class="container my-4">
    <h2 class="mt-4">Movies:</h2>
    <div class="row row-cols-1 row-cols-md-2 row-cols-md-3 row-cols-md-4 g-5">
        {% for movie in content_movies %}
          <div class="col">
            <a href="{% url 'subscriber:movie_info' movie.id %}" class="text-decoration-none text-dark">
              <div class="card big-item">
                <img src="{{ movie.image.url }}" class="card-img-top" height="200rem" alt="{{ movie.title }}" />
                <div class="card-body">
                  <div class="card-title"> {{movie.title}}</div>
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
  </div>
{% endblock %}

moz_plus_project/subscriber/templates/subscriber/mylist.html
{% extends 'home/base.html' %}

{% block body %}
{% include 'home/navbar.html' %}
     {% for each in mylist %}
            <img width="200" src="media/{{each.image}}"><br/>
            {% if each.movie is None %}
            <a href="{% url 'subscriber:home_path' %}movieinfo/{{movies.id}}">
                <button type="button" class="btn btn-secondary">View info and details</button>
            </a>
            {% else %}
            <a href="{% url 'subscriber:home_path' %}seriesinfo/{{series.id}}">
                <button type="button" class="btn btn-secondary">View info and details</button>
            </a>
             <br><br>
            {% endif %}
     {% endfor %}
{% endblock %}

moz_plus_project/subscriber/templates/subscriber/series.html
{% extends 'home/base.html' %}

{% block body %}
  {% include 'home/navbar.html' %}
  {% block style %}
    <style>
      .big-item {
        transition: transform 0.3s; /* Add transition for smooth effect */
      }
      
      .big-item:hover {
        transform: scale(1.1); /* Enlarge the element on hover */
      }
    </style>
  {% endblock %}

  <div class="container my-4">
    <h2>Series:</h2>

    <div class="row row-cols-1 row-cols-md-2 row-cols-md-3 row-cols-md-4 g-5">
      {% for serie in content_series %}
        <div class="col">
          <a href="{% url 'subscriber:series_details' serie.id %}" class="text-decoration-none text-dark">
            <div class="card big-item">
              <img src="{{ serie.image.url }}" class="card-img-top" height="200rem" alt="{{ serie.title }}" />
              <div class="card-body">
                <div class="card-title">{{ serie.title }}</div>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

moz_plus_project/subscriber/templates/subscriber/series_details.html
{% extends 'home/base.html' %}

{% block body %}
  {% include 'home/navbar.html' %}
  <div class="container">
    <div class="card bg-secondary">
      <img src="{{ content_series.image.url }}" class="rounded" alt="{{ content_series.slug }}" />
      <div class="card-img-overlay" style="background-color: rgba(0, 0, 0, 0.6);">
        <div class="row text-light h-100">
          <div class="col-6">
            <div class="d-flex flex-column justify-content-around h-100">
              <div class="fs-2 fw-bold">{{ content_series.title }}</div>
              <div class="fs-6">{{ content_series.overview }}</div>
            </div>
          </div>
          <div class="col-6">
            <div class="d-flex flex-column justify-content-center h-100">
              <div class="row">
                <div class="col">
                  <div class="fs-5">Release Date</div>
                </div>
                <div class="col">
                  <div class="fs-6">{{ content_series.created_date }}</div>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-4">
                  <div class="card-text fs-5">Genre</div>
                </div>
                <div class="col-8">
                  {% for genre in content_series.genre.all %}
                    <span class="badge rounded-pill bg-primary my-1 p-2">{{ genre.name }}</span>
                  {% endfor %}
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-4">
                  <div class="card-text fs-5">Studio</div>
                </div>
                <div class="col-8">
                  {% for studio in content_season.studio.all %}
                    <div class="row">
                      <div class="col-3">
                        <img src="{{ studio.image.url }}" alt="" width="48" height="48" class="rounded-circle me-2" />
                      </div>
                      <div class="col-9">{{ studio.name }}</div>
                    </div>
                  {% endfor %}
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <div class="fs-5">Favourite</div>
                </div>
                <div class="col">
                  <form action="" method="POST">
                    {% csrf_token %}
                    <button class="btn" type="submit" name="favourite">
                      {% if favourite %}
                        <i class="bi bi-star-fill fs-2 text-warning"></i>
                      {% else %}
                        <i class="bi bi-star fs-2 text-warning"></i>
                      {% endif %}
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card bg-secondary my-2">
      <div class="card-body row justify-content-between p-2">
        <div class="col">
          <div class="fs-5">Season:</div>
        </div>
        <div class="col">
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Season {{ content_season.season_no }}</button>
            <ul class="dropdown-menu">
              {% for season in content_seasons %}
                <li>
                  <a class="dropdown-item" href="{% url 'subscriber:series_details' content_series.id season.id %}">Season {{ season.season_no }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="my-2 overflow-auto" style="height: 80vh;">
      <div class="row row-cols-1 row-cols-md-2 row-cols-md-3 g-2" style="width: 85vw;">
        {% for episode in content_episodes %}
          <div class="col">
            <div class="card" style="width: 22rem;">
              <div class="row">
                <div class="col">
                  <a href="{% url 'subscriber:episode_details' content_series.id content_season.id episode.id %}" class="text-decoration-none text-dark"><img src="{{ episode.thumbnail.url }}" class="card-img-top" alt="{{ episode.slug }}" /></a>
                </div>
                <div class="col">
                  <div class="card-body text-dark">
                    <div class="d-flex flex-column justify-content-between" style="height: 14rem;">
                      <div class="card-title">{{ episode.title|slice:'30' }}</div>
                      <div class="card-text">Ratings: {{ episode.average_rating }}</div>
                      <a href="{{ episode.video.url }}" class="btn btn-primary"><i class="bi bi-play-btn"></i></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

    <div class="my-2">
      <div class="fs-2 fw-bold">Trailers</div>
      <div class="d-flex flex-row flex-nowrap overflow-auto">
        {% for trailer in content_season_trailer %}
          <div class="embed-responsive embed-responsive-4by3">
            <iframe src="{{ trailer.url }}" class="embed-responsive-item mx-2" title="YouTube video" allowfullscreen></iframe>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

moz_plus_project/subscriber/templates/subscriber/subscriber.html
{% extends 'home/base.html' %}

{% block body %}
{% include 'home/navbar.html' %}
<div class="container">

</div>
{% endblock body %}