moz_plus_project/home/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
)

from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="home"),
    path("accounts/login/", views.user_login, name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path(
        "accounts/password-change/",
        PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password-change-done/",
        PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("register/", views.subscriber_registration, name="register"),
    path(
        "content-creator/register/", views.creator_registration, name="register_creator"
    ),
    path("home/series/", views.series, name="series"),
    path(
        "home/series/<int:series_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "home/series/<int:series_id>/<int:season_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "home/series/<int:series_id>/<int:season_id>/<int:episode_id>/",
        views.episode_details,
        name="episode_details",
    ),
    path("home/movies/", views.movies, name="movies"),
    path("home/movie-info/<int:passed_id>/", views.movie_info, name="movie_info"),
    path(
        "home/movie-part/<int:movie_part_id>/",
        views.movie_part_details,
        name="movie_part_details",
    ),
]

moz_plus_project/moz_plus_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('super_admin.urls')),
    path('', include('subscriber.urls')),
    path('', include('content_creator.urls')),
    path('', include('content_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moz_plus_project/super_admin/urls.py
from django.urls import path

from . import views

app_name = "super_admin"

urlpatterns = [
    path("super/admin/", views.admin_super, name="super_admin"),
    path("super/admin/value/add/<str:active>", views.add_values, name="add_values"),
    path(
        "super/admin/value/edit/<str:active>/<int:active_id>",
        views.edit_values,
        name="edit_values",
    ),
    path(
        "super/admin/value/delete/<str:active>/<int:active_id>",
        views.delete_values,
        name="delete_values",
    ),
]

moz_plus_project/super_admin/models.py
from django.db import models


# Create your models here.
class Country(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Language(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class ContentRating(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)
    age = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.name


class Genre(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class ShowRole(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Studio(models.Model):
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to="super_admin/studio/images")
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class SubscriptionPlan(models.Model):
    name = models.CharField(max_length=100)
    cost = models.DecimalField(max_digits=3, decimal_places=2)
    months = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.name

moz_plus_project/super_admin/forms.py
from django import forms

from .models import (
    ContentRating,
    Country,
    Genre,
    Language,
    ShowRole,
    Studio,
    SubscriptionPlan,
)


class AddCountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ("name",)


class EditCountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ("name",)


class AddLanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = ("name",)


class EditLanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = ("name",)


class AddContentRatingForm(forms.ModelForm):
    class Meta:
        model = ContentRating
        fields = (
            "name",
            "age",
        )


class EditContentRatingForm(forms.ModelForm):
    class Meta:
        model = ContentRating
        fields = (
            "name",
            "age",
        )


class AddGenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ("name",)


class EditGenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ("name",)


class AddShowRoleForm(forms.ModelForm):
    class Meta:
        model = ShowRole
        fields = ("name",)


class EditShowRoleForm(forms.ModelForm):
    class Meta:
        model = ShowRole
        fields = ("name",)


class AddStudioForm(forms.ModelForm):
    class Meta:
        model = Studio
        fields = (
            "name",
            "image",
            "country",
        )


class EditStudioForm(forms.ModelForm):
    class Meta:
        model = Studio
        fields = (
            "name",
            "image",
            "country",
        )


class AddSubscriptionPlanForm(forms.ModelForm):
    class Meta:
        model = SubscriptionPlan
        fields = (
            "name",
            "cost",
            "months",
        )


class EditSubscriptionPlanForm(forms.ModelForm):
    class Meta:
        model = SubscriptionPlan
        fields = (
            "name",
            "cost",
            "months",
        )

moz_plus_project/super_admin/views.py
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from . import forms


# Create your views here.
@login_required
def admin_super(request):
    menus = [
        "Country",
        "Language",
        "ContentRating",
        "Genre",
        "ShowRole",
        "Studio",
        "SubscriptionPlan",
    ]
    active = request.GET.get("active") or menus[0]
    values = apps.get_model("super_admin", active).objects.all()

    context = {
        "menus": menus,
        "active": active,
        "values": values,
    }
    return render(request, "super_admin/super_admin.html", context)


@login_required
def add_values(request, active):
    admin_forms = {
        "Country": forms.AddCountryForm,
        "Language": forms.AddLanguageForm,
        "ContentRating": forms.AddContentRatingForm,
        "Genre": forms.AddGenreForm,
        "ShowRole": forms.AddShowRoleForm,
        "Studio": forms.AddStudioForm,
        "SubscriptionPlan": forms.AddSubscriptionPlanForm,
    }

    if request.method == "POST":
        form = admin_forms.get(active)(request.POST)
        if form.is_valid():
            form.save()
            return redirect(
                reverse("super_admin:super_admin") + "?active=" + active,
            )

    else:
        form = admin_forms.get(active)()

    return render(
        request,
        "super_admin/add_values.html",
        context={
            "form": form,
            "active": active,
        },
    )


@login_required
def edit_values(request, active, active_id):
    admin_forms = {
        "Country": forms.EditCountryForm,
        "Language": forms.EditLanguageForm,
        "ContentRating": forms.EditContentRatingForm,
        "Genre": forms.EditGenreForm,
        "ShowRole": forms.EditShowRoleForm,
        "Studio": forms.EditStudioForm,
        "SubscriptionPlan": forms.EditSubscriptionPlanForm,
    }
    values = apps.get_model("super_admin", active).objects.get(id=active_id)

    if request.method == "POST":
        form = admin_forms.get(active)(request.POST, instance=values)
        if form.is_valid():
            form.save()
            return redirect(
                reverse("super_admin:super_admin") + "?active=" + active,
            )

    else:
        form = admin_forms.get(active)(instance=values)

    return render(
        request,
        "super_admin/edit_values.html",
        context={
            "form": form,
            "active": active,
        },
    )


@login_required
def delete_values(request, active, active_id):
    value = apps.get_model("super_admin", active).objects.get(id=active_id)
    value.delete()
    
    return redirect(
        reverse("super_admin:super_admin") + "?active=" + active,
    )

moz_plus_project/super_admin/templates/super_admin/add_values.html
{% extends 'home/base.html' %}

{% load crispy_forms_tags %}

{% block body %}
<div class="container m-5">
    <form class="form" method="post">
        {% csrf_token %}
        <h4>{{active}}</h4>
        <hr>
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add Content</button>
    </form>

</div>

{% endblock %}

moz_plus_project/super_admin/templates/super_admin/edit_values.html
{% extends 'home/base.html' %}

{% load crispy_forms_tags %}

{% block body %}
<div class="container m-5">
    <form class="form" method="post">
        {% csrf_token %}
        <h4>{{active}}</h4>
        <hr>
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>

{% endblock %}

moz_plus_project/super_admin/templates/super_admin/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'super_admin:super_admin' %}">
            <img src="{% static 'images/mozlogo.svg' %}" alt="Moz Logo" width="92"/>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="mx-5">
            <h2>Admin Dashboard</h2>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav ms-auto">
                {% if request.user.is_authenticated %}
                <a class="btn btn-outline-success nav-link" href="{% url 'home:logout' %}">Logout</a>
                {% else %}
                <a class="btn btn-outline-success nav-link" href="{% url 'home:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

moz_plus_project/super_admin/templates/super_admin/sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark sticky-top" style="width: 280px;">
    <div class="mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <span class="fs-5">Manage</span>
    </div>
    <hr>
    {% for menu in menus %}
    <ul class="nav nav-pills flex-column mb-auto">
        {% if menu == active %}
        <li class="nav-item">
            <a href="?active={{menu}}" class="nav-link active" aria-current="page">
                {{menu}}
            </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a href="?active={{menu}}" class="nav-link text-white">
                {{menu}}
            </a>
        </li>
        {% endif %}
    </ul>
    {% endfor %}
</div>

moz_plus_project/super_admin/templates/super_admin/super_admin.html
{% extends 'home/base.html' %}

{% block body %}
{% include 'super_admin/navbar.html' %}

<div class="row w-100 my-2">
    <div class="col-3">
        {% include 'super_admin/sidebar.html' %}

    </div>
    <div class="col-9">
        <div class="table-responsive card">
            <table class="table table-light table-hover table-striped">
                <thead>
                <tr>
                    <th colspan="2">{{active}}</th>
                    <th>
                        <a class="btn btn-primary" href="{% url 'super_admin:add_values' active %}">
                            <i class="bi bi-plus-square"></i>
                        </a>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for value in values%}
                <tr>
                    <td>
                        <div class="w-75 p-1">
                            {{value.name}}
                        </div>
                    </td>
                    <td>
                        <a href="{% url 'super_admin:edit_values' active value.id %}">
                            <i class="bi bi-pencil-square fs-5"></i>
                        </a>
                    </td>
                    <td>
                        <i data-object-id="{% url 'super_admin:delete_values' active value.id %}" class="bi bi-trash3-fill fs-5 text-danger delete-object"></i>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    const elements = document.getElementsByClassName('delete-object');
    for(let i = 0; i < elements.length; i++){
        const objectID = elements[i].getAttribute('data-object-id');
        elements[i].addEventListener('click', function() {
            var ask = confirm('Are you want to delete?');
            if (ask && objectID) {
                window.location.href = objectID;
            }
            return false;
        });
    }
</script>
{% endblock body %}