moz_plus_project/content_creator/urls.py
from django.urls import path


from . import views
from .views import (
    add_season,
    add_episode,
    edit_season,
    delete_season,
    delete_episode,
    add_series,
    edit_episode,
    add_movies,
    edit_moviepart,
    add_moviespart,
    edit_movie,
    delete_movie,
    delete_moviepart,
    edit_series,
    delete_series,
)

app_name = "content_creator"

urlpatterns = [
    path("content-creator/", views.content_creator, name="content_creator"),
    path("content-creator/series/", views.series, name="series"),
    path("content-creator/movies/", views.movies, name="movies"),
    path(
        "content-creator/series/<int:series_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "content-creator/series/<int:series_id>/<int:season_id>/",
        views.series_details,
        name="series_details",
    ),
    path("content-creator/add-season/<int:series_id>/", add_season, name="add_season"),
    path("content-creator/add-episode/<int:season_id>/", add_episode, name="add_episode"),
    path(
        "content-creator/edit-season/<int:series_id>/<int:passed_id>/", edit_season, name="edit_season"
    ),
    path(
        "content-creator/delete_season/<int:season_id>/",
        delete_season,
        name="delete_season",
    ),
    path(
        "content-creator/delete_episode/<int:episode_id>/",
        delete_episode,
        name="delete_episode",
    ),
    path("content-creator/add-series/", add_series, name="add_series"),
    path(
        "content-creator/edit-episode/<int:season_id>/<int:passed_id>/",
        edit_episode,
        name="edit_episode",
    ),
    path(
        "content-creator/movie-details/<int:movie_id>/",
        views.movie_details,
        name="movies_details",
    ),
    path("content-creator/add-movies/", add_movies, name="add_movies"),
    path("content-creator/add-moviepart/<int:movie_id>/", add_moviespart, name="add_moviepart"),
    path("content-creator/edit-movie/<int:passed_id>/", edit_movie, name="edit_movie"),
    path(
        "content-creator/edit-moviepart/<int:passed_id>/",
        edit_moviepart,
        name="edit_moviepart",
    ),
    path(
        "content-creator/delete-movie/<int:movie_id>/",
        delete_movie,
        name="delete_movie",
    ),
    path(
        "content-creator/delete-moviepart/<int:moviepart_id>/",
        delete_moviepart,
        name="delete_moviepart",
    ),
    path(
        "content-creator/edit-series/<int:passed_id>/", edit_series, name="edit_series"
    ),
    path(
        "content-creator/delete-series/<int:series_id>/",
        delete_series,
        name="delete_series",
    ),
]

moz_plus_project/home/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
)

from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="home"),
    path("accounts/login/", views.user_login, name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path(
        "accounts/password-change/",
        PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password-change-done/",
        PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("register/", views.subscriber_registration, name="register"),
    path(
        "content-creator/register/", views.creator_registration, name="register_creator"
    ),
    path("home/series/", views.series, name="series"),
    path(
        "home/series/<int:series_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "home/series/<int:series_id>/<int:season_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "home/series/<int:series_id>/<int:season_id>/<int:episode_id>/",
        views.episode_details,
        name="episode_details",
    ),
    path("home/movies/", views.movies, name="movies"),
    path("home/movie-info/<int:passed_id>/", views.movie_info, name="movie_info"),
    path(
        "home/movie-part/<int:movie_part_id>/",
        views.movie_part_details,
        name="movie_part_details",
    ),
]

moz_plus_project/moz_plus_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('super_admin.urls')),
    path('', include('subscriber.urls')),
    path('', include('content_creator.urls')),
    path('', include('content_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moz_plus_project/content_creator/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django import forms
from .models import MoviePart, Series, Season, Episodes, Movie

from .forms import (
    AddMoviesForm,
    EditMovieForm,
    EditMoviePartForm,
    AddMoviePartForm,
    EditEpisodesForm,
    EditSeasonForm,
    EditSerieForm,
    MovieTrailerAddform,
)


from .forms import SeriesForm, SeasonForm, EpisodesForm
from crispy_bootstrap5.bootstrap5 import FloatingField
from django.contrib.auth.decorators import login_required


from . import models


@login_required
# Create your views here.
def content_creator(request):
    moz_user = models.ContentCreator.objects.get(user=request.user)
    return render(
        request, "content_creator/content_creator.html", {"moz_user": moz_user}
    )


@login_required
def series(request):
    moz_user = models.ContentCreator.objects.get(user=request.user)

    search = request.GET.get("search")

    if search:
        content_series = models.Series.objects.filter(creator=moz_user, title__icontains=search,)
    else:
        content_series = models.Series.objects.filter(creator=moz_user)

    context = {"content_series": content_series, "moz_user": moz_user}
    return render(request, "content_creator/series.html", context)


@login_required
def series_details(request, series_id=None, season_id=None):
    moz_user = models.ContentCreator.objects.get(user=request.user)

    content_series = models.Series.objects.get(id=series_id)
    content_seasons = models.Season.objects.filter(series_id=series_id)

    content_episodes = None
    content_season = None
    if season_id:
        content_season = models.Season.objects.get(id=season_id)
        content_episodes = models.Episodes.objects.filter(season_id=season_id)
    elif content_seasons:
        content_season = models.Season.objects.get(id=content_seasons.first().id)
        content_episodes = models.Episodes.objects.filter(
            season_id=content_seasons.first().id
        )

    search = request.GET.get("search")
    if search:
        content_episodes = content_episodes.filter(title__icontains=search)

    context = {
        "content_series": content_series,
        "content_seasons": content_seasons,
        "content_episodes": content_episodes,
        "content_season": content_season,
        "moz_user": moz_user,
    }
    return render(request, "content_creator/series_details.html", context)


@login_required
def add_season(request, series_id):
    if request.method == "POST":
        add_season_form = SeasonForm(request.POST, request.FILES)
        if add_season_form.is_valid():
            new_season = add_season_form.save(commit=False)
            new_season.post_author = request.user
            new_season.series_id = series_id
            new_season.save()

            return redirect(
                "content_creator:series_details", new_season.series.id, new_season.id
            )
    else:
        add_season_form = SeasonForm()
        return render(
            request,
            "content_creator/add_season.html",
            context={"add_season_form": add_season_form},
        )


@login_required
def add_episode(request, season_id):
    if request.method == "POST":
        add_episode_form = EpisodesForm(request.POST, request.FILES)
        if add_episode_form.is_valid():
            new_episode = add_episode_form.save(commit=False)
            new_episode.post_author = request.user
            new_episode.season_id = season_id
            new_episode.save()
            return redirect(
                "content_creator:series_details",
                new_episode.season.series.id,
                new_episode.season.id,
            )

    else:
        add_episode_form = EpisodesForm()

    return render(
        request,
        "content_creator/add_episode.html",
        context={"add_episode_form": add_episode_form},
    )


@login_required
def edit_season(request, series_id, passed_id):
    # get the get method var and passing  that along with the model
    season_details = get_object_or_404(Season, id=passed_id)
    edit_season_form = EditSeasonForm(
        request.POST or None, request.FILES or None, instance=season_details
    )
    if edit_season_form.is_valid():
        new_season = edit_season_form.save(commit=False)
        new_season.series_id = series_id
        new_season.save()
        return redirect(
            "content_creator:series_details", new_season.series.id, new_season.id
        )

    return render(
        request,
        "content_creator/edit_season.html",
        context={"edit_season_form": edit_season_form},
    )


@login_required
def edit_episode(request, season_id, passed_id):
    # get the get method var and passing  that along with the model
    episode_details = Episodes.objects.get(id=passed_id)
    edit_episode_form = EditEpisodesForm(
        request.POST or None, request.FILES or None, instance=episode_details
    )
    if edit_episode_form.is_valid():
        new_episode = edit_episode_form.save(commit=False)
        new_episode.season_id = season_id
        new_episode.save()
        return redirect(
            "content_creator:series_details",
            new_episode.season.series.id,
            new_episode.season.id,
        )

    return render(
        request,
        "content_creator/edit_episode.html",
        context={"edit_episode_form": edit_episode_form},
    )


@login_required
def delete_season(request, season_id):
    content_season = models.Season.objects.get(id=season_id)
    series_id = content_season.series.id
    content_season.delete()
    return redirect("content_creator:series_details", series_id)


# deleting the episode
@login_required
def delete_episode(request, episode_id):
    # get the get method var and passing  that along with the model
    content_episode = models.Episodes.objects.get(id=episode_id)
    season = content_episode.season
    content_episode.delete()
    return redirect("content_creator:series_details", season.series.id, season.id)


@login_required
def add_series(request):
    moz_user = models.ContentCreator.objects.get(user=request.user)

    if request.method == "POST":
        add_series_form = SeriesForm(request.POST, request.FILES)
        if add_series_form.is_valid():
            new_series = add_series_form.save(commit=False)
            new_series.creator = moz_user
            new_series.save()
            add_series_form.save_m2m()

            return redirect("content_creator:series")
    else:
        add_series_form = SeriesForm()

    return render(
        request, "content_creator/add_series.html", {"add_series_form": add_series_form}
    )


@login_required
def movies(request):
    moz_user = models.ContentCreator.objects.get(user=request.user)

    search = request.GET.get("search")
    if search:
        content_movies = models.Movie.objects.filter(creator=moz_user, title__icontains=search)
    else:
        content_movies = models.Movie.objects.filter(creator=moz_user)

    context = {"content_movies": content_movies, "moz_user": moz_user}
    return render(request, "content_creator/movies.html", context)


@login_required
def movie_details(request, movie_id):
    moz_user = models.ContentCreator.objects.get(user=request.user)

    content_movie = models.Movie.objects.get(id=movie_id)
    content_moviepart = models.MoviePart.objects.filter(movie_id=movie_id)

    search = request.GET.get("search")
    if search:
        content_moviepart = content_moviepart.filter(title__icontains=search)

    context = {
        "moz_user": moz_user,
        "content_movie": content_movie,
        "content_moviepart": content_moviepart,
    }
    return render(request, "content_creator/movie_details.html", context)


@login_required
def add_movies(request):
    moz_user = models.ContentCreator.objects.get(user=request.user)

    if request.method == "POST":
        add_movies_form = AddMoviesForm(request.POST, request.FILES)
        if add_movies_form.is_valid():
            new_movies = add_movies_form.save(commit=False)
            new_movies.creator = moz_user
            new_movies.save()
            add_movies_form.save_m2m()
            return redirect("content_creator:movies")
    else:
        add_movies_form = AddMoviesForm()

    return render(
        request, "content_creator/add_movies.html", {"add_movies_form": add_movies_form}
    )


@login_required
def add_moviespart(request, movie_id):
    if request.method == "POST":
        add_moviespart_form = AddMoviePartForm(request.POST, request.FILES)
        add_movietrailer_form = MovieTrailerAddform(request.POST)

        if add_moviespart_form.is_valid():
            new_moviepart = add_moviespart_form.save(commit=False)
            new_moviepart.movie_id = movie_id
            new_moviepart.save()
            new_movietrailer = add_movietrailer_form.save(commit=False)
            new_movietrailer.movie_part = new_moviepart
            new_movietrailer.save()
            return redirect("content_creator:movies_details", new_moviepart.movie.id)
    else:
        add_moviespart_form = AddMoviePartForm()
        add_movietrailer_form = MovieTrailerAddform()
    return render(
        request,
        "content_creator/add_moviepart.html",
        {
            "add_moviespart_form": add_moviespart_form,
            "add_movietrailer_form": add_movietrailer_form,
        },
    )


@login_required
def edit_movie(request, passed_id):
    # get the get method var and passing  that along with the model
    movie_details = get_object_or_404(Movie, id=passed_id)
    edit_movie_form = EditMovieForm(
        request.POST or None, request.FILES or None, instance=movie_details
    )
    if edit_movie_form.is_valid():
        new_movie = edit_movie_form.save(commit=False)
        new_movie.save()
        return redirect("content_creator:movies")

    return render(
        request,
        "content_creator/edit_movies.html",

moz_plus_project/content_creator/templates/content_creator/add_episode.html
{% extends 'home/base.html' %}

{% block title %}
  <title>Add Episode</title>
{% endblock %}
{% load crispy_forms_tags %}
{% block body %}
  <div class="container my-20">
    <h4>Episode</h4>
    <hr />
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
      {% csrf_token %}
      {{ add_episode_form|crispy }}
      <input type="submit" value="Add" class="btn btn-primary" />
    </form>
  </div>
{% endblock %}

moz_plus_project/content_creator/templates/content_creator/add_moviepart.html
{% extends 'home/base.html' %}

{% block title %}
  <title>Add Movies</title>
{% endblock %}
{% load crispy_forms_tags %}

{% block body %}
  <div class="container my-3">
    <h4>Movies</h4>
    <hr />
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
      {% csrf_token %}
      {{ add_moviespart_form|crispy }}
      {{ add_movietrailer_form|crispy }}
      <input type="submit" value="Save" class="btn btn-success" />
    </form>
  </div>
{% endblock %}

moz_plus_project/content_creator/templates/content_creator/add_movies.html
  {% extends 'home/base.html' %}

{% load crispy_forms_tags %}

{% block title %}
<title>
    Add Movie
</title>
{% endblock title %}

{% block body %}
 <div class="container m-5">
     <form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h4>Movies</h4>
    <hr>
    {{ add_movies_form|crispy }}

    <button type="submit" class="btn btn-primary">Add Content</button>
</form>

 </div>

{% endblock %}

moz_plus_project/content_creator/templates/content_creator/add_season.html
{% extends 'home/base.html' %}

{% block title %}
  <title>Add Season</title>
{% endblock title%}
{% load crispy_forms_tags %}
{% block body %}
  <div class="container my-2">
    <h4>Season</h4>
    <hr/>
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
      {% csrf_token %}
      {{ add_season_form|crispy }}
      <input type="submit" value="Add" class="btn btn-primary" />
    </form>
  </div>
{% endblock %}

moz_plus_project/content_creator/templates/content_creator/add_series.html
{% extends 'home/base.html' %}

{% block title %}
  <title>Add Series</title>
{% endblock %}

{% load crispy_forms_tags %}

{% block body %}
  <div class="container my-2">
    <h4>Series</h4>
    <hr />
    <form class="form" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ add_series_form|crispy }}
      <button type="submit" class="btn btn-primary">Add</button>
    </form>
  </div>
{% endblock %}

moz_plus_project/content_creator/templates/content_creator/content_creator.html
{% extends 'home/base.html' %}

{% block body %}
{% include 'home/navbar.html' %}
<div class="container">

</div>
{% endblock body %}

moz_plus_project/content_creator/templates/content_creator/edit_episode.html
{% extends 'home/base.html' %}

{% block title %}
  <title>Edit Episode</title>
{% endblock %}
{% load crispy_forms_tags %}

{% block body %}
  <div class="container my-3">
    <h4>Episode</h4>
    <hr />
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
      {% csrf_token %}
      {{ edit_episode_form|crispy }}
      <input type="submit" value="Save" class="btn btn-primary" />
    </form>
  </div>
{% endblock %}

moz_plus_project/content_creator/templates/content_creator/edit_moviepart.html
{% extends 'home/base.html' %}

{% block title %}
  <title>Edit Movie</title>
{% endblock %}
{% load crispy_forms_tags %}

{% block body %}
  <div class="container my-3">
    <h4>Movies</h4>
    <hr/>
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
      {% csrf_token %}
      {{ edit_moviepart_form|crispy }}
      <input type="submit" value="Update" class="btn btn-success" />
    </form>
  </div>
{% endblock %}

moz_plus_project/content_creator/templates/content_creator/edit_season.html
{% extends 'home/base.html' %}

{% block title %}
  <title>Edit Season</title>
{% endblock %}
{% load crispy_forms_tags %}

{% block body %}
  <div class="container my-3">
    <h4>Episode</h4>
    <hr />
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
      {% csrf_token %}
      {{ edit_season_form|crispy }}
      <input type="submit" value="Save" class="btn btn-primary" />
    </form>
  </div>
{% endblock %}

moz_plus_project/content_creator/templates/content_creator/edit_series.html
   {% extends 'home/base.html' %}

   {% block title %} <title>Edit Series</title>{% endblock title %}

{% load crispy_forms_tags %}

{% block body %}
  <div class="container my-2">
    <h2>Series</h2>
    <hr>
     <form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ edit_series_form|crispy }}

    <button type="submit" class="btn btn-primary">Edit </button>
</form>

 </div>

{% endblock %}

moz_plus_project/content_creator/templates/content_creator/movie_details.html
{% extends 'home/base.html' %}

{% block body %}
  {% include 'home/navbar.html' %}
  <div class="container">
    <div class="card bg-secondary">
      <img src="{{ content_movie.image.url }}" class="rounded" alt="{{ content_movie.slug }}" width="250px" />
      <div class="card-img-overlay">
        <div class="row justify-content-between h-100">
          <h5 class="card-title fs-2">{{ content_movie.title }}</h5>
          <p class="card-text">{{ content_movie.overview }}...</p>
          <div class="row justify-content-end">
            <p class="card-text col-2">
              <small>{{ content_movie.created_date|date:'M d, Y' }}</small>
            </p>
          </div>
          <div class="row justify-content-end">
            <div class="col-1">
              <a href="{% url 'content_creator:edit_movie' content_movie.id %}" class="btn btn-primary">Edit</a>
            </div>
            <div class="col-1">
              <a href="{% url 'content_creator:delete_movie' content_movie.id %}" class="btn btn-danger">Delete</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card text-dark mt-4 mb-2 p-1">
      <div class="row justify-content-between align-items-center">
        <div class="col-2">
          <p class="fs-4 fw-bold">Movies</p>
        </div>
        <div class="col-2">
          <a href="{% url 'content_creator:add_moviepart' content_movie.id %}" class="btn btn-primary">Add Movies</a>
        </div>
      </div>
    </div>

    {% for moviepart in content_moviepart %}
      <div class="card mb-3 text-dark w-50">
        <div class="row">
          <div class="col-4">
            <img src="{{ moviepart.thumbnail.url }}" class="img-fluid rounded-start w-75" alt="{{ moviepart.slug }}" />
          </div>
          <div class="col-8">
            <div class="card-body">
              <h5 class="card-title">{{ moviepart.title }}</h5>
              <p class="card-text">{{ moviepart.plot|slice:':50' }}</p>
              <p class="card-text">
                <small class="text-body-secondary">{{ moviepart.created_date|date:'M d, Y' }}</small>
              </p>
              <a href="{% url 'content_creator:edit_moviepart' moviepart.id %}" class="btn btn-success">Edit</a>
              <a href="{% url 'content_creator:delete_moviepart' moviepart.id %}" class="btn btn-danger">Delete</a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

moz_plus_project/content_creator/templates/content_creator/movies.html
{% extends 'home/base.html' %}

{% block body %}
  {% include 'home/navbar.html' %}

  <div class="row justify-content-between mx-2 vw-75">
    <div class="col-auto">
      <h4>Movies:</h4>
    </div>
    <div class="col-auto">
      <a href="{% url 'content_creator:add_movies' %}" class="btn btn-danger">Add</a>
    </div>
  </div>
  <div class="container my-2">
    {% regroup content_movies|dictsortreversed:'updated_date' by updated_date|date:'Y M' as movie_list %}
    {% for movies in movie_list %}
      <div class="card mt-4 mb-2 p-2 text-dark text-center">
        <div class="fs-4 fw-bold">{{ movies.grouper }}</div>
      </div>
      <div class="row row-cols-1 row-cols-md-2 row-cols-md-3 row-cols-md-4">
        {% for movie in movies.list %}
          <div class="col">
            <a href="{% url 'content_creator:movies_details' movie.id %}" class="text-decoration-none text-dark">
              <div class="card my-2">
                <img src="{{ movie.image.url }}" class="card-img-top" height="200rem" alt="{{ movie.title }}" />
                <div class="card-body">
                  <div class="card-title"> {{movie.title}}</div>
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

moz_plus_project/content_creator/templates/content_creator/series.html
{% extends 'home/base.html' %}

{% block body %}
  {% include 'home/navbar.html' %}

  <div class="row justify-content-between mx-2 vw-75">
    <div class="col-auto">
      <h4>Series:</h4>
    </div>
    <div class="col-auto">
      <a href="{% url 'content_creator:add_series' %}" class="btn btn-danger">Add</a>
    </div>
  </div>
  <div class="container my-2">
    {% regroup content_series|dictsortreversed:'updated_date' by updated_date|date:'Y M' as series_list %}
    {% for series in series_list %}
      <div class="card mt-4 mb-2 text-dark text-center">
        <div class="fs-4 fw-bold">{{ series.grouper }}</div>
      </div>
      <div class="row row-cols-1 row-cols-md-2 row-cols-md-3 row-cols-md-4">
        {% for serie in series.list %}
          <div class="col">
            <a href="{% url 'content_creator:series_details' serie.id %}" class="text-decoration-none text-dark">
              <div class="card my-2">
                <img src="{{ serie.image.url }}" class="card-img-top" height="200rem" alt="{{ serie.title }}" />
                <div class="card-body">
                    <div class="card-title"> {{serie.title}}</div>
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

moz_plus_project/content_creator/templates/content_creator/series_details.html
{% extends 'home/base.html' %}

{% block body %}
  {% include 'home/navbar.html' %}
  <div class="container">
    <div class="card bg-secondary">
      <img src="{{ content_series.image.url }}" class="rounded" alt="{{ content_series.slug }}" />
      <div class="card-img-overlay">
        <div class="row justify-content-between h-100">
          <h5 class="card-title fs-2">{{ content_series.title }}</h5>
          <p class="card-text">{{ content_series.overview }}...</p>
          <div class="row justify-content-end">
            <p class="card-text col-2">
              <small>{{ content_series.created_date|date:'M d, Y' }}</small>
            </p>
          </div>
          <div class="row justify-content-end">
            <div class="col-1">
              <a href="{% url 'content_creator:edit_series' content_series.id %}" class="btn btn-primary">Edit</a>
            </div>
            <div class="col-1">
              <a href="{% url 'content_creator:delete_series' content_series.id %}" class="btn btn-danger">Delete</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row align-items-center justify-content-between my-2">
      {% if content_season %}
        <div class="col">
          <div class="card bg-secondary">
            <div class="card-body row justify-content-between p-2">
              <div class="col">
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Season {{ content_season.season_no }}</button>
                  <ul class="dropdown-menu">
                    {% for season in content_seasons %}
                      <li>
                        <a class="dropdown-item" href="{% url 'content_creator:series_details' content_series.id season.id %}">Season {{ season.season_no }}</a>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
              <div class="col">
                <a href="{% url 'content_creator:edit_season' content_series.id content_season.id %}" class="btn btn-primary">Edit</a>
              </div>
              <div class="col">
                <a href="{% url 'content_creator:delete_season' content_season.id %}" class="btn btn-danger">Delete</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-2">
          <a href="{% url 'content_creator:add_season' content_series.id %}" class="btn btn-primary">Add Season</a>
        </div>
        <div class="col-2">
          <a href="{% url 'content_creator:add_episode' content_season.id %}" class="btn btn-primary">Add Episode</a>
        </div>
      {% else %}
        <div class="col">
          <a href="{% url 'content_creator:add_season' content_series.id %}" class="btn btn-primary">Add Season</a>
        </div>
      {% endif %}
    </div>

    {% for episode in content_episodes %}
      <div class="card mb-3 text-dark w-50">
        <div class="row">
          <div class="col-4">
            <img src="{{ episode.thumbnail.url }}" class="img-fluid rounded-start w-75" alt="{{ episode.slug }}" />
          </div>
          <div class="col-8">
            <div class="card-body">
              <h5 class="card-title">{{ episode.title }}</h5>
              <p class="card-text">{{ episode.plot|slice:':50' }}</p>
              <p class="card-text">
                <small class="text-body-secondary">{{ episode.created_date|date:'M d, Y' }}</small>
              </p>
              <a href="{% url 'content_creator:edit_episode' content_season.id episode.id %}" class="btn btn-success">Edit</a>
              <a href="{% url 'content_creator:delete_episode' episode.id %}" class="btn btn-danger">Delete</a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}