moz_plus_project/content_creator/urls.py
from django.urls import path


from . import views
from .views import (
    add_season,
    add_episode,
    edit_season,
    delete_season,
    delete_episode,
    add_series,
    edit_episode,
    add_movies,
    edit_moviepart,
    add_moviespart,
    edit_movie,
    delete_movie,
    delete_moviepart,
    edit_series,
    delete_series,
)

app_name = "content_creator"

urlpatterns = [
    path("content-creator/", views.content_creator, name="content_creator"),
    path("content-creator/series/", views.series, name="series"),
    path("content-creator/movies/", views.movies, name="movies"),
    path(
        "content-creator/series/<int:series_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "content-creator/series/<int:series_id>/<int:season_id>/",
        views.series_details,
        name="series_details",
    ),
    path("content-creator/add-season/<int:series_id>/", add_season, name="add_season"),
    path("content-creator/add-episode/<int:season_id>/", add_episode, name="add_episode"),
    path(
        "content-creator/edit-season/<int:series_id>/<int:passed_id>/", edit_season, name="edit_season"
    ),
    path(
        "content-creator/delete_season/<int:season_id>/",
        delete_season,
        name="delete_season",
    ),
    path(
        "content-creator/delete_episode/<int:episode_id>/",
        delete_episode,
        name="delete_episode",
    ),
    path("content-creator/add-series/", add_series, name="add_series"),
    path(
        "content-creator/edit-episode/<int:season_id>/<int:passed_id>/",
        edit_episode,
        name="edit_episode",
    ),
    path(
        "content-creator/movie-details/<int:movie_id>/",
        views.movie_details,
        name="movies_details",
    ),
    path("content-creator/add-movies/", add_movies, name="add_movies"),
    path("content-creator/add-moviepart/<int:movie_id>/", add_moviespart, name="add_moviepart"),
    path("content-creator/edit-movie/<int:passed_id>/", edit_movie, name="edit_movie"),
    path(
        "content-creator/edit-moviepart/<int:passed_id>/",
        edit_moviepart,
        name="edit_moviepart",
    ),
    path(
        "content-creator/delete-movie/<int:movie_id>/",
        delete_movie,
        name="delete_movie",
    ),
    path(
        "content-creator/delete-moviepart/<int:moviepart_id>/",
        delete_moviepart,
        name="delete_moviepart",
    ),
    path(
        "content-creator/edit-series/<int:passed_id>/", edit_series, name="edit_series"
    ),
    path(
        "content-creator/delete-series/<int:series_id>/",
        delete_series,
        name="delete_series",
    ),
]

moz_plus_project/home/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
)

from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="home"),
    path("accounts/login/", views.user_login, name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path(
        "accounts/password-change/",
        PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password-change-done/",
        PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("register/", views.subscriber_registration, name="register"),
    path(
        "content-creator/register/", views.creator_registration, name="register_creator"
    ),
    path("home/series/", views.series, name="series"),
    path(
        "home/series/<int:series_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "home/series/<int:series_id>/<int:season_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "home/series/<int:series_id>/<int:season_id>/<int:episode_id>/",
        views.episode_details,
        name="episode_details",
    ),
    path("home/movies/", views.movies, name="movies"),
    path("home/movie-info/<int:passed_id>/", views.movie_info, name="movie_info"),
    path(
        "home/movie-part/<int:movie_part_id>/",
        views.movie_part_details,
        name="movie_part_details",
    ),
]

moz_plus_project/moz_plus_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('super_admin.urls')),
    path('', include('subscriber.urls')),
    path('', include('content_creator.urls')),
    path('', include('content_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moz_plus_project/subscriber/urls.py
from django.urls import path

from . import views

app_name = 'subscriber'

urlpatterns = [
    path('subscriber/', views.subscriber, name='subscriber'),
    path('subscriber/series/', views.series, name='series'),
    path(
        "subscriber/series/<int:series_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "subscriber/series/<int:series_id>/<int:season_id>/",
        views.series_details,
        name="series_details",
    ),
    path(
        "subscriber/series/<int:series_id>/<int:season_id>/<int:episode_id>/",
        views.episode_details,
        name="episode_details",
    ),
    path('subscriber/movies/', views.movies, name='movies'),
    path('subscriber/movie-info/<int:passed_id>/', views.movie_info, name='movie_info'),
    path('subscriber/movie-part/<int:movie_part_id>/', views.movie_part_details, name='movie_part_details'),
    path('subscriber/favourites/', views.favourites, name='favourites'),
]

moz_plus_project/home/models.py
from django.db import models

# Create your models here.

moz_plus_project/home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.contrib.auth.password_validation import (
    validate_password,
    MinimumLengthValidator,
    NumericPasswordValidator,
)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        data = self.cleaned_data.get("username")
        user = User.objects.filter(username=data)

        if not user:
            raise forms.ValidationError("Username not found.")

        return data

    def clean(self):
        data = super().clean()
        username = data.get("username")
        password = data.get("password")

        user = User.objects.filter(username=username).first()

        if user and not user.check_password(password):
            raise forms.ValidationError("Username or Password not match.")

        return data


class UserRegistrationForm(forms.ModelForm):
    username_validator = ASCIIUsernameValidator()

    username = forms.CharField(
        label="Username",
        widget=forms.TextInput,
        max_length=20,
        help_text="Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.",
        validators=[username_validator],
    )

    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput,
        max_length=20,
    )

    confirm_password = forms.CharField(
        label="Confirm Password", widget=forms.PasswordInput, max_length=20
    )

    class Meta:
        model = User
        fields = ("username", "first_name", "email", "password")

    def clean_password(self):
        password = self.cleaned_data.get("password")
        min_length_validator = MinimumLengthValidator()
        password_validator = NumericPasswordValidator()

        validate_password(
            password, password_validators=[min_length_validator, password_validator]
        )
        raise password

    def clean_confirm_password(self):
        cd = self.cleaned_data

        if cd.get("password", "") != cd["confirm_password"]:
            raise forms.ValidationError("Password not matching")

        return cd["confirm_password"]


class CreatorRegistrationForm(forms.ModelForm):

    username_validator = ASCIIUsernameValidator()

    username = forms.CharField(
        label="Username",
        widget=forms.TextInput,
        max_length=20,
        help_text="Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.",
        validators=[username_validator],
    )

    password = forms.CharField(
        label="Password", widget=forms.PasswordInput, max_length=20
    )
    confirm_password = forms.CharField(
        label="Confirm Password", widget=forms.PasswordInput, max_length=20
    )

    class Meta:
        model = User
        fields = ("username", "first_name", "email", "password")

    def clean_password(self):
        password = self.cleaned_data.get("password")
        min_length_validator = MinimumLengthValidator()
        password_validator = NumericPasswordValidator()

        validate_password(
            password, password_validators=[min_length_validator, password_validator]
        )
        raise password

    def clean_confirm_password(self):
        cd = self.cleaned_data

        if cd.get("password", "") != cd["confirm_password"]:
            raise forms.ValidationError("Password not matching")

        return cd["confirm_password"]

moz_plus_project/home/views.py
from django.apps import apps
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect

from . import forms


# Create your views here.
def home(request):
    return render(request, "home/home.html")


def user_login(request):
    if request.method != "POST":
        form = forms.LoginForm()
    else:
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            auth = authenticate(
                request,
                username=data["username"],
                password=data["password"],
            )

            if auth is not None:
                login(request, auth)
                if request.user.is_superuser:
                    return redirect("super_admin:super_admin")
                elif request.user.groups.all().first().name == "content_creator":
                    return redirect("content_creator:content_creator")
                elif request.user.groups.all().first().name == "subscriber":
                    return redirect("subscriber:subscriber")

    context = {"form": form}
    return render(request, "registration/login.html", context)


def subscriber_registration(request):
    if request.method != "POST":
        form = forms.UserRegistrationForm()
    else:
        form = forms.UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data["password"])
            new_user.save()
            group_reviewer = Group.objects.get(name="subscriber")
            new_user.groups.add(group_reviewer)

            return redirect("subscriber:subscriber")

    context = {"form": form}
    return render(request, "accounts/user_registration.html", context)


def creator_registration(request):
    if request.method != "POST":
        form = forms.CreatorRegistrationForm()
    else:
        form = forms.CreatorRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data["password"])
            new_user.save()
            group_reviewer = Group.objects.get(name="content_creator")
            new_user.groups.add(group_reviewer)

            return redirect("content_creator:content_creator")

    context = {"form": form}
    return render(request, "accounts/creator_registration.html", context)


def movies(request):
    search = request.GET.get("search")

    if search:
        content_movies = apps.get_model(
            app_label="content_creator", model_name="Movie"
        ).objects.filter(title__icontains=search)
    else:
        content_movies = apps.get_model(
            app_label="content_creator", model_name="Movie"
        ).objects.all()

    context = {"content_movies": content_movies}
    return render(request, "home/movie/movies.html", context)


def movie_info(request, passed_id):
    content_movies = apps.get_model(
        app_label="content_creator", model_name="Movie"
    ).objects.get(id=passed_id)

    content_movies_part = apps.get_model(
        app_label="content_creator", model_name="MoviePart"
    ).objects.filter(movie_id=passed_id)

    context = {
        "content_movies": content_movies,
        "content_movies_part": content_movies_part,
    }

    return render(request, "home/movie/movie_info.html", context)


def movie_part_details(request, movie_part_id):
    content_movies_part = apps.get_model(
        app_label="content_creator", model_name="MoviePart"
    ).objects.get(id=movie_part_id)

    content_movie_rating = (
        apps.get_model(app_label="content_management", model_name="ShowRatingMoviePart")
        .objects.filter(movie_part=content_movies_part)
        .first()
    )

    content_movie_trailer = apps.get_model(
        app_label="content_creator", model_name="MovieTrailer"
    ).objects.filter(movie_part_id=movie_part_id)

    context = {
        "content_movies_part": content_movies_part,
        "content_movie_rating": content_movie_rating,
        "content_movie_trailer": content_movie_trailer,
    }
    return render(request, "home/movie/moviepart_details.html", context)


def series(request):
    search = request.GET.get("search")

    if search:
        content_series = apps.get_model(
            app_label="content_creator", model_name="Series"
        ).objects.filter(title__icontains=search)
    else:
        content_series = apps.get_model(
            app_label="content_creator", model_name="Series"
        ).objects.all()

    context = {
        "content_series": content_series,
    }
    return render(request, "home/series/series.html", context)


def series_details(request, series_id, season_id=None):
    content_series = apps.get_model(
        app_label="content_creator", model_name="Series"
    ).objects.get(id=series_id)

    content_seasons = apps.get_model(
        app_label="content_creator", model_name="Season"
    ).objects.filter(series_id=series_id)

    content_season_id = season_id or content_seasons.first().id

    content_season = apps.get_model(
        app_label="content_creator", model_name="Season"
    ).objects.get(id=content_season_id)

    content_episodes = apps.get_model(
        app_label="content_creator", model_name="Episodes"
    ).objects.filter(season_id=content_season_id)

    content_season_trailer = apps.get_model(
        app_label="content_creator", model_name="SeasonTrailer"
    ).objects.filter(season_id=content_season_id)

    context = {
        "content_series": content_series,
        "content_season": content_season,
        "content_seasons": content_seasons,
        "content_episodes": content_episodes,
        "content_season_trailer": content_season_trailer,
    }
    return render(request, "home/series/series_details.html", context)


def episode_details(request, series_id, season_id, episode_id):
    content_episode = apps.get_model(
        app_label="content_creator", model_name="Episodes"
    ).objects.get(id=episode_id)

    context = {
        "content_episode": content_episode,
    }
    return render(request, "home/series/episode_details.html", context)

moz_plus_project/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% load static %}
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    {% block style %}{% endblock style %}
    {% block title %} {% endblock title %}
</head>
<body class="bg-dark text-light">
{% block body %} {% endblock body %}
{% bootstrap_javascript %}
</body>
</html>

moz_plus_project/home/templates/home/footerbar.html
<footer class="bg-dark text-light p-5">
    <div class="row align-items-start">
        <div class="col-6 col-md-2 mb-3">
            <h5>Account</h5>
            <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="{% url 'home:register' %}" class="nav-link p-0 text-body-secondary">Account</a></li>
                <li class="nav-item mb-2"><a href="{% url 'home:register_creator' %}" class="nav-link p-0 text-body-secondary">Creator Account</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Redeem Gift Cards</a>
                </li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Privacy</a></li>
            </ul>
        </div>

        <div class="col-6 col-md-2 mb-3">
            <h5>Contact Moz<sup>+</sup>&nbsp;</h5>
            <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Terms of Use</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Privacy</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Help Center</a></li>
            </ul>
        </div>

        <div class="col-md-5 offset-md-1 mb-3">
            <form>
                <h5>Subscribe to our newsletter</h5>
                <p>Monthly digest of what's new and exciting from us.</p>
                <div class="d-flex flex-column flex-sm-row w-100 input-group mb-3">
                    <label for="newsletter1" class="visually-hidden">Email address</label>
                    <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                    <button class="btn btn-danger" type="button">Subscribe</button>
                </div>
            </form>
        </div>
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
        <p>© 2023 Moz<sup>+</sup>, Inc. All rights reserved.</p>
        <ul class="list-unstyled d-flex">
            <li class="ms-3"><a class="link-body-emphasis" href="#">
                <i class="bi bi-twitter" style="color: white"></i>
            </a></li>
            <li class="ms-3"><a class="link-body-emphasis" href="#">
                <i class="bi bi-instagram" style="color: white"></i>
            </a></li>
            <li class="ms-3"><a class="link-body-emphasis" href="#">
                <i class="bi bi-facebook" style="color: white"></i>
            </a></li>
        </ul>
    </div>
</footer>

moz_plus_project/home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'style.css' %}" />
{% endblock %}

{% block title %}
<title>Moz</title>
{% endblock %}

{% block body %}
{% include 'home/navbar.html' %}

<div class="header">
    <div class="header-content">
        <h1>Unlimited movies, TV shows and more.</h1>
        <h3>Watch anywhere. Cancel anytime.</h3>
        <p>Ready to watch? Enter your email to create or restart your membership.</p>
        <a class="btn btn-danger nav-link text-white" href="{% url 'home:register' %}">Register</a>
    </div>
</div>

<div class="features">
    <div class="row">
        <div class="text-col">
            <h2>Enjoy on your TV.</h2>
            <p>Watch on smart TVs, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray players and more.</p>
        </div>
        <div class="img-col">
            <img src="{% static 'assets/feature-1.png' %}" alt="feature-1" />
        </div>
    </div>
    <div class="row">
        <div class="img-col">
            <img src="{% static 'assets/feature-2.png' %}" alt="feature-2" />
        </div>
        <div class="text-col">
            <h2>Download your shows to watch offline.</h2>
            <p>Save your favourites easily and always have something to watch.</p>
        </div>
    </div>
    <div class="row">
        <div class="text-col">
            <h2>Watch everywhere.</h2>
            <p>Stream unlimited movies and TV shows on your phone, tablet, laptop, and TV.</p>
        </div>
        <div class="img-col">
            <img src="{% static 'assets/feature-3.png' %}" alt="feature-3" />
        </div>
    </div>
    <div class="row">
        <div class="img-col">
            <img src="{% static 'assets/feature-4.png' %}" alt="feature-4" />
        </div>
        <div class="text-col">
            <h2>Create profiles for children.</h2>
            <p>Send children on adventures with their favourite characters in a space made just for them—free with your
                membership.</p>
        </div>
    </div>
</div>

<div class="faq">
    <h2>Frequently Asked Questions</h2>

    <div class="accordion" id="accordionExample">
        <div class="accordion-item bg-dark text-light">
            <h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">What is
                    Moz<sup>+</sup>?</button></h2>
            <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    Moz<sup>+</sup> is a streaming service that offers a wide variety of award-winning TV shows,
                    movies,
                    anime, documentaries and more – on thousands of internet-connected devices.<br /><br />
                    You can watch as much as you want, whenever you want, without a single ad – all for one low monthly
                    price.
                    There's always something new to discover, and new TV shows and movies are added every week!
                </div>
            </div>
        </div>
        <div class="accordion-item bg-dark text-light">
            <h2 class="accordion-header"><button class="accordion-button collapsed" type="button"
                    data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false"
                    aria-controls="collapseTwo">How much does
                    Moz<sup>+</sup> cost?</button></h2>
            <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    Watch Moz<sup>+</sup> on your smartphone, tablet, Smart TV, laptop, or streaming device, all
                    for one
                    fixed monthly fee. Plans range from ₹ 149 to ₹ 649 a month. No extra costs, no contracts.
                </div>
            </div>
        </div>
        <div class="accordion-item bg-dark text-light">
            <h2 class="accordion-header"><button class="accordion-button collapsed" type="button"
                    data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false"
                    aria-controls="collapseThree">Where can I
                    watch?</button></h2>
            <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    Watch anywhere, anytime. Sign in with your Moz<sup>+</sup> account to watch instantly on the
                    web at
                    Moz<sup>+</sup>.com from your personal computer or on any internet-connected device that
                    offers the
                    Moz<sup>+</sup>
                    app, including smart TVs, smartphones, tablets, streaming media players and game
                    consoles.<br /><br />
                    You can also download your favourite shows with the iOS, Android, or Windows 10 app. Use downloads
                    to watch
                    while you're on the go and without an internet connection. Take Moz<sup>+</sup> with you
                    anywhere.
                </div>
            </div>
        </div>
        <div class="accordion-item bg-dark text-light">
            <h2 class="accordion-header"><button class="accordion-button collapsed" type="button"
                    data-bs-toggle="collapse" data-bs-target="#collapseFourth" aria-expanded="false"
                    aria-controls="collapseFourth">How do I
                    cancel?</button></h2>
            <div id="collapseFourth" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    Moz<sup>+</sup> is flexible. There are no annoying contracts and no commitments. You can
                    easily cancel
                    your account online in two clicks. There are no cancellation fees – start or stop your account
                    anytime.
                </div>
            </div>
        </div>
        <div class="accordion-item bg-dark text-light">
            <h2 class="accordion-header"><button class="accordion-button collapsed" type="button"
                    data-bs-toggle="collapse" data-bs-target="#collapsefifth" aria-expanded="false"
                    aria-controls="collapsefifth">What can I watch on
                    Moz<sup>+</sup>?</button></h2>
            <div id="collapsefifth" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    Moz<sup>+</sup> has an extensive library of feature films, documentaries, TV shows, anime,
                    award-winning
                    Moz<sup>+</sup> originals, and more. Watch as much as you want, anytime you want.
                </div>
            </div>
        </div>
        <div class="accordion-item bg-dark text-light">
            <h2 class="accordion-header"><button class="accordion-button collapsed" type="button"
                    data-bs-toggle="collapse" data-bs-target="#collapseSixth" aria-expanded="false"
                    aria-controls="collapseSixth">Is Moz<sup>+</sup>
                    good for Kids?</button></h2>
            <div id="collapseSixth" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    Moz<sup>+</sup> Kids experience is included in your membership to give parents control while
                    kids enjoy
                    family-friendly TV shows and films in their own space.<br /><br />
                    Kids profiles come with PIN-protected parental controls that let you restrict the maturity rating of
                    content
                    kids can watch and block specific titles you don’t want kids to see.
                </div>
            </div>
        </div>
    </div>

    <small>Ready to watch? Enter your email to create or restart your membership.</small>
</div>
{% include 'home/footerbar.html' %}
{% endblock %}

moz_plus_project/home/templates/home/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        {% load static %}
        {% if request.user.is_authenticated and request.user.groups.all.0.name == 'subscriber' %}
        <a class="navbar-brand" href="{% url 'subscriber:subscriber' %}">
            <img src="{% static 'images/mozlogo.svg' %}" alt="Moz Logo" width="92"/>
        </a>
        {% elif request.user.is_authenticated and request.user.groups.all.0.name == 'content_creator' %}
        <a class="navbar-brand" href="{% url 'content_creator:content_creator' %}">
            <img src="{% static 'images/mozlogo.svg' %}" alt="Moz Logo" width="92"/>
        </a>
        {% else %}
        <a class="navbar-brand" href="{% url 'home:home' %}">
            <img src="{% static 'images/mozlogo.svg' %}" alt="Moz Logo" width="92"/>
        </a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if request.user.is_authenticated and request.user.groups.all.0.name == 'subscriber' %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'subscriber:series' %}">TV Shows</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'subscriber:movies' %}">Movies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'subscriber:favourites' %}">Favourites</a>
                </li>
            </ul>
            {% elif request.user.is_authenticated and request.user.groups.all.0.name == 'content_creator' %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'content_creator:series' %}">TV Shows</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'content_creator:movies' %}">Movies</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:series' %}">TV Shows</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:movies' %}">Movies</a>
                </li>
            </ul>
            {% endif %}

            {% if request.user.is_authenticated %}
            <form class="d-flex">
                <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search" />
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <div class="dropdown m-2" style="width: 150px;">
                <div class="d-flex justify-content-end text-white text-decoration-none dropdown-toggle"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{{ moz_user.image.url }}" alt="" width="32" height="32"
                        class="rounded-circle me-2" />
                    <strong>{{ request.user.username }}</strong>
                </div>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1" style="">
                    <li>
                        <a class="dropdown-item" href="#">Profile</a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'home:logout' %}">Log out</a>
                    </li>
                </ul>
            </div>
            <div class="me-2"></div>
            {% else %}
            <a class="btn btn-danger nav-link text-white" href="{% url 'home:login' %}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>